//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public System.Guid Id { get; set; }
        public System.Guid CategoryId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImageContentType { get; set; }
        public string ImageBase64String { get; set; }
        public double Price { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
